#+TITLE: README for Discrete Mathematics Two (aka DM2 aka CS 238)
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+STARTUP: showeverything

  Welcome to Discrete Mathematics Two!

  This is a blurb for those who are coming back after a few semesters' gap since DM1:

  This is very possibly the first .org file you have seen. It won't be the last!
  There are many, many things you can do in emacs/Spacemacs/org-mode that you
  will learn in this course. One of them is that links in this file can be
  visited either in the usual way by clicking on them, or else by positioning
  the cursor on them and typing SPC u Ctrl-c Ctrl-o. This key sequence only
  works in org-mode under emacs/Spacemacs. No other editor, including the one
  GitHub provides, supports org-mode. Instructions on how to start using
  emacs/Spacemacs and unearth the power of org-mode will be forthcoming. In the
  meantime, since .org files are "plain old text" files (marked up in clever
  ways), any old editor will do.

* Course Metamaterial

   [[file:syllabus.org][syllabus.org]]

   [[file:schedule.org][schedule.org]]

   [[file:grading.org][grading.org]]

   [[file:see-grades.org][see-grades.org]]

* Course Material

   [[https://rickneff.github.io][The Book]]

   [[file:wa00.org][wa00.org]]
