#+TITLE: Schedule
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+STARTUP: showeverything

  Simple. Regular. Predictable. Such is this semester's schedule.

  There are assignments of ever-increasing weight due every week, including this
  week I'm numbering 00, excluding the last week of the semester (finals week).
  The 00 Assignment is due Saturday, January 7th, 2017, at 6:00 PM MST. Every
  assignment thereafter is also due by 6:00 PM MST on Saturday. A grace period
  of up to 6 hours will be granted, but the points earned will be diminished by
  a "Timeliness" factor that is factored into the weighted score for each
  assignment. The [[file:see-grades.org][see-grades.org]] file shows how. This factor is initially 1.0,
  but decreases as a function of elapsed time starting at the 6:00 hour and
  ending at midnight, or the submission time, whichever comes first. If the
  submission time is midnight or later, the factor drops to zero. Provision may
  be made on occasion for a factor that is greater than one, rewarding early
  submissions.

  A similar mechanism governs preparation assessments, with the following
  differences:

  - Preparation assessments are weighted equally, each at 2.5% of the total
    grade.
  - Each week's PA is due by 3:15 PM MST (class starting time) on Wednesday (the
    third class meeting of each week).

  (Re)reading [[https://rickneff.github.io][The Book]] is another regular activity you are tasked with. There
  are three main sections and essentially three months (12 full weeks) in the
  semester. That's one main section per month, or about one subsection every
  week. More details will be available in each week's preparation assessment.
