#+TITLE: Software Engineering
#+DATE: <2017-01-05 Thu>
#+AUTHOR: Colton Kopsa
#+EMAIL: Aghbac@Aghbac.local
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t c:nil creator:comment d:(not "LOGBOOK") date:t
#+OPTIONS: e:t email:nil f:t inline:t num:t p:nil pri:nil stat:t
#+OPTIONS: tags:t tasks:t tex:t timestamp:t toc:t todo:t |:t
#+CREATOR: Emacs 25.1.1 (Org mode 8.2.10)
#+DESCRIPTION:
#+EXCLUDE_TAGS: noexport
#+KEYWORDS:
#+LANGUAGE: en
#+SELECT_TAGS: export

* Acronyms
- SRS - Software Requirement Specification
- SDD - System Design Document

* Business Model
- Sell things for 3x the manufacturing cost
- How you start a company is angel investors
  - Have more than 1,000,000 dollars
  - Registered with the FCC
- Then you go to venture capitalists
  - Worry about making money quickly
    - Lots of money in 5 years
- Can we do it?
  - Do we have the technology?
- Should we do it?
  - Will it improve our brand/company
* Role
** Project Manager
   The project we are working on is Peerfessional Reviews, we plan to accomplish
   writing a SRS document as well as a SDD. Both teams will use the parallel
   strategy pattern to accomplish this project. As Project manager I will be
   guiding the overall software development process in the direction of the
   requirements to which the stake-holders and my team agree. I will be
   answering questions that team leaders pose to me. I will meet weekly with the
   division manager (Br. Grimmett) to resolve questions that my team has that I
   am unable to answer. I will organize and l|      |          |          |               |
ead out in meetings that require
   the entire team, and strive to support in meetings held by team leaders. I
   will review completed tasks of the teams to ensure that tasks are done
   correctly and meet the requirements agreed on. I will establish regular
   contact with team leaders to discuss team needs and help create plans to
   fulfill those needs. Document control will be decided on a team basis, but
   teams were leaning towards Independent control, where parts of the document
   would be set up as tasks and then completed by team members. We will be using
   Trello as a task management tool and Slack as a group chat for the team as a
   whole. Trello will be used for Kanban on our team. All tasks will be
   represented on Trello, and then individual members of a team can assign
   themselves tasks. When a task is picked up it will move from the open task
   list to the in progress list. When the task is ready to be reviewed it will
   move to that list. When the task is finished it will move to the finished
   list. Doing this will allow teams to understand what is going on, what is
   finished, and what needs to be done.
* Elicitation Presentation
** Team DL
   - Introspection
     - Good explanation of what introspection is.
   - Semi-Structured Interviews
