#+TITLE: webdev1
#+DATE: <2017-01-05 Thu>
#+AUTHOR: Colton Kopsa
#+EMAIL: Aghbac@Aghbac.local
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t c:nil creator:comment d:(not "LOGBOOK") date:t
#+OPTIONS: e:t email:nil f:t inline:t num:t p:nil pri:nil stat:t
#+OPTIONS: tags:t tasks:t tex:t timestamp:t toc:t todo:t |:t
#+CREATOR: Emacs 25.1.1 (Org mode 8.2.10)
#+DESCRIPTION:
#+EXCLUDE_TAGS: noexport
#+KEYWORDS:
#+LANGUAGE: en
#+SELECT_TAGS: export
* 01
** Teach One Another : Web Technology Discussion
What are some of the most popular IDEs or editors for web development
today?  

Free & Open Source: Atom 

Atom is a simple, yet extensible text editor built by GitHub for web
development. It has a built in package manager that allows one to
quickly add/remove features to improve productivity. It works
cross-platform, so anyone using a Windows, Mac, or Linux machine can
use it. It provides auto-completion, file system browsing, and find
and replace over an entire project.

Proprietary: WebStorm

WebStorm is a lot heavier of an application, but provides a more
polished product. It has all the features stated about Atom, but adds
code inspection with quick-fixes, coding assistance with popular
frameworks, and debugging features.

Sources:
https://www.jetbrains.com/webstorm/features/
https://atom.io
http://ourcodeworld.com/articles/read/200/top-7-best-free-web-development-ide-for-javascript-html-and-css
** Ponder : Internet & Web Jargon
1. AJAX
   - asynchronous JavaScript and XML
   - used to create asynchronous web applications
   - allows you to change page content without loading a new URL
   - Programming the World Wide Web - pg 5
   - http://www.w3schools.com/xml/ajax_intro.asp
2. applet
   - used to provide interactive features to web applications that
     cannot be provided by HTML alone
   - limited control on content outside of the applet's designated
     area.
   - written in Java
   - Examples:
     - Quicktime
     - Flash
   - https://en.wikipedia.org/wiki/Applet#Web-based_Applets
   - https://netbeans.org/kb/docs/web/applets.html
3. Bootstrap framework
   - free and open-source
   - HTML and CSS based
   - Only for front-end development
   - Built to increase consistency of front-end structure
   - the most popular HTML, CSS, and JS framework for developing
     responsive, mobile first projects on the web.
   - https://en.wikipedia.org/wiki/Bootstrap_(front-end_framework)
   - http://getbootstrap.com/#content
4. CGI (common gateway interface)
   - Used to create a "gateway" to legacy information systems,
     existing documents, or an existing database through an HTTP
     server.
   - an agreement between implementors about how to design/integrate gateways
   - offers a standard protocol for web servers to interface with
     executable programs running on a server that generate web pages
     dynamically.
   - https://www.w3.org/CGI/
   - https://en.wikipedia.org/wiki/Common_Gateway_Interface
5. client 
   - recipients of data from a server/servers
   - request documents from servers and display them to users
   - a computer program that, as part of its operation, relies on
     sending a request to another computer program
   - Programming the World Wide Web - pg 7
   - Programming the World Wide Web - pg 5
   - https://en.wikipedia.org/wiki/Client_(computing)
6. CSS
   - describes how HTML elements should be displayed
   - can control multiple HTML pages
   - a style sheet language used for describing the presentation of a
     document written in a markup language
   - https://en.wikipedia.org/wiki/Cascading_Style_Sheets
   - http://www.w3schools.com/css/css_intro.asp
7. DHTML
   - an umbrella term for a collection of technologies used together
     to create interactive and animated web sites
   - uses a combination of a static markup language, a client-side
     scripting language, a presentation definition language, and the
     Document Object Model.
   - https://en.wikipedia.org/wiki/Dynamic_HTML
   - http://w3schools.sinsixx.com/dhtml/dhtml_intro.asp.htm
8. DNS
   - a hierarchical decentralized naming system for computers,
     services, or any resource connected to the Internet or a private
     network
   - translates domain names to numerical IP addresses
   - domain names are converted to IP addresses through name servers
   - https://en.wikipedia.org/wiki/Domain_Name_System
   - Programming the World Wide Web - pg 5
9. ethernet
   - a system for connecting a number of computer systems to form a
     local area network
   - uses protocols to control the passing of information and to avoid
     simultaneous transmission by two or more systems.
   - a family of computer networking technologies commonly used in
     local area networks and metropolitan area networks
   - https://en.wikipedia.org/wiki/Ethernet
   - Google Definition
10. FTP
    - the commonly used protocol for exchanging files over the Internet
    - uses the Internet's TCP/IP protocols to enable data transfer
    - http://www.webopedia.com/TERM/F/ftp.html
    - Programming the World Wide Web - pg 5
11. HTML
    - Hyper Text Markup Language
    - the standard markup language for creating Web pages
    - describes and defines the content of a webpage
    - http://www.w3schools.com
    - https://developer.mozilla.org/en-US/docs/Web/HTML
12. HTTP
    - provides communication interface for connections between browsers and Web servers
    - the foundation of data communication for the World Wide Web
    - https://en.wikipedia.org/wiki/Wikipedia:Protection_policy#pc1
    - Programming the World Wide Web - pg 2
13. IP address
    - a unique 32-bit number that represents the address of a computer connected to the internet
    - a unique string of numbers separated by periods that identifies each computer using the  Internet Protocol to communicate over a network
    - Programming the World Wide Web - pg 4
    - Google Definition
14. JQuery
    - a cross-platform JavaScript library designed to simplify the
      client-side scripting of HTML
    - makes things like HTML document traversal and manipulation,
      event handling, animation, and Ajax much simpler with an
      easy-to-use API that works across a multitude of browsers
    - https://en.wikipedia.org/wiki/JQuery
    - https://jquery.com/
15. MIME
    - Multipurpose Internet Mail Extension
    - developed to specify format of different kinds of documents
    - originally used with internet mail, but was adopted to the Web
    - a standard for formatting files of different types, such as
      text, graphics, or audio, so they can be sent over the Internet
      and seen or played by a web browser or e-mail application.
    - Programming the World Wide Web - pg 12
    - Google Definition
16. ping
    - query (another computer on a network) to determine whether there
      is a connection to it.
    - a computer network administration software utility used to test
      the reachability of a host on an Internet Protocol (IP) network
    - Google Definition
    - https://en.wikipedia.org/wiki/Ping_(networking_utility)
17. router
    - a device that forwards data packets to the appropriate parts of
      a computer network
    - perform the traffic directing functions on the Internet
    - Google Definition
    - https://en.wikipedia.org/wiki/Router_(computing)
18. server
    - hosts data and provides it to clients over a network
    - a computer program or a device that provides functionality for
      other programs or devices, called "clients"
    - Programming the World Wide Web - pg 2
    - https://en.wikipedia.org/wiki/Server_(computing)
19. servlet
    - a Java class
    - executed on the server system
    - produces an HTML document as a response
    - a small, server-resident program that typically runs
      automatically in response to user input
    - Google Definition
    - Programming the World Wide Web - pg 26
20. SQL
    - Structured Query Language
    - a special-purpose domain-specific language used in programming
      and designed for managing data held in a relational database
      management system (RDBMS), or for stream processing in a
      relational data stream management system (RDSMS).
    - a standard language for accessing databases
    - http://www.w3schools.com/sql/
    - https://en.wikipedia.org/wiki/SQL
21. SSH
    - a cryptographic network protocol for operating network services
      securely over an unsecured network
    - a program for logging into a remote machine and for executing
      commands on a remote machine
    - https://en.wikipedia.org/wiki/Secure_Shell
    - http://linuxcommand.org/man_pages/ssh1.html
22. SSL
    - the standard security technology for establishing an encrypted
      link between a web server and browser.
    - cryptographic protocols that provide communications security
      over a computer network
    - http://info.ssl.com/article.aspx?id=10241
    - https://en.wikipedia.org/wiki/Transport_Layer_Security
23. TCP/IP
    - Transmission Control Protocol/Internet Protocol
    - used to allow a program on one computer to communicate with a
      program on another computer via the Internet
    - the conceptual model and set of communications protocols used on
      the Internet and similar computer networks
    - https://en.wikipedia.org/wiki/Internet_protocol_suite
    - Programming the World Wide Web - pg 3
24. telnet (this is also an acronym)
    - a popular protocol that runs on top of TCP/IP
    - allows one user on the Internet to log on to another computer on the Internet
    - a network protocol that allows a user on one computer to log
      onto another computer that is part of same network
    - Google Definition
    - Programming the World Wide Web - pg 5
25. traceroute
    - a computer network diagnostic tool for displaying the route
      (path) and measuring transit delays of packets across an
      Internet Protocol (IP) network
    - tracks the path of data between two points
    - http://www.whatsmyip.org/traceroute/
    - https://en.wikipedia.org/wiki/Traceroute
26. unicode
    - provides a unique number for every character
    - a computing industry standard for the consistent encoding,
      representation, and handling of text expressed in most of the
      world's writing systems
    - http://unicode.org/standard/WhatIsUnicode.html
    - https://en.wikipedia.org/wiki/Unicode
27. URL
    - specify addresses of resources found on the Web
    - a reference to a web resource that specifies its location on a
      computer network and a mechanism for retrieving it
    - Programming the World Wide Web - pg 2
    - https://en.wikipedia.org/wiki/Uniform_Resource_Locator
28. UTF-8
    - UTF-8 is a compromise character encoding that can be as compact
      as ASCII (if the file is just plain English text) but can also
      contain any unicode characters (with some increase in file
      size).
    - a character encoding capable of encoding all possible
      characters, or code points, defined by Unicode
    - https://en.wikipedia.org/wiki/UTF-8
    - http://www.fileformat.info/info/unicode/utf8.htm
29. W3C
    - World Wide Web Consortium
    - primary purpose was to develop and distribute standards for Web technologies
    - an international community that develops open standards to
      ensure the long-term growth of the Web
    - https://www.w3.org/
    - Programming the World Wide Web - pg 35
30. xDSL
    - a family of technologies that are used to transmit digital data
      over telephone lines
    - https://en.wikipedia.org/wiki/Digital_subscriber_line
    - http://www.webopedia.com/TERM/X/xDSL.html
31. XHTML
    - eXtensible HTML
    - redefinintion of HTML 4.01 using XML
    - mirrors or extends versions of the widely used Hypertext Markup
      Language (HTML)
    - https://en.wikipedia.org/wiki/Digital_subscriber_line
    - Programming the World Wide Web - pg 35
32. XML
    - eXtensible Markup Language
    - allows users to create their own markup language defining tags
      and attributes for application at hand
    - designed to store and transport data and be self-descriptive
    - Programming the World Wide Web - pg 23
    - http://www.w3schools.com/xml/xml_whatis.asp
33. XSL
    - a language for expressing style sheets
    - used to refer to a family of languages used to transform and
      render XML documents
    - https://www.w3.org/Style/XSL/WhatIsXSL.html
    - https://en.wikipedia.org/wiki/XSL
* 02
** Teach One Another : Style Guide
*** Copyright
    - "There is no such thing, by the way, as a copyright for your website. When
      you register copyright for online material, you have to identify each
      individual element of the site that qualifies for copyright protection.
      For example: text, music, recordings, video, photographs, etc. Registering
      online material is (for that reason) more complicated than just
      registering single works." - https://www.astuteo.com/articles/stolen-website-design
    - This quote stresses that it's the content of a page that is more of a
      concern for copyright and not necessarily the page layout.
    - There is a difference in practical programming practices and stealing
      intellectual property
    - Reuse of open source code can be used when the code it's being added to
      follows the same licensing
    - If unable to determine the license being used, it should be assumed that
      it is not allowed to be used.
#+BEGIN_SRC html :tangle week03.html
  <!DOCTYPE html>
  <html>
    <head>
	    <title>Week 03 : CSS</title>
	    <meta charset="UTF-8">	

	    <!-- STYLESHEET 1 . . . Diaz-Nunez, Jose -->	
	    <style>    
	      #bottom, p {
	      color: black;
	      font-family: "Agency FB";
	      font-size: 24px;
	      }

	      #title p {
	      text-align: center;
	      color: white;
	      font-size: 30px;
	      font-weight: bold;
	      }

	      .document {
        background-image: 
        url(https://images3.pixlis.com/background-image-stripes-and-lines-seamless-tileable-old-gold-black-bean-2323pz.png);
        background-color: #cccccc;
	      display: block;
	      max-width: 700px;
	      margin: auto;
	      border: 5px solid #fff;
        }

        #title {
        background-color: #00afea;
	      display: block;
	      max-width: 650px;
	      margin: auto;
	      border: 5px solid #fff;
        }

        #title h1 {
        text-shadow: 2px 2px 3px #632dbd;
        color: white;
        text-transform: uppercase; 
        font-family: "SimSun-ExtB";
        font-weight: bold;
        font-size: 70px;
        text-align: center;
        }

        .content {
        background-color: #632dbd;
	      display: block;
	      max-width: 650px;
	      margin: auto;
	      border: 5px solid #fff;
        }

        #menuBar {
        background-color: #00afea;
	      display: block;
	      max-width: 599px;
	      margin: auto;
	      border: 0px 5px solid #fff;
	      padding: 0px;
        }

        #menuBar ul {
    	  color: #fff;
        margin: 8;
        overflow: hidden;
        background-color: black;
        text-align: left;
        font: normal small-caps normal medium "Helvetica";
        }

        #menuBar li {
    	  display: inline;
    	  float: left;
        }

        #menuBar li a:hover:not(.active) {
        background-color: orange;
        color: white;
        }

        .menuBarItem {
        padding: 1px;
        }

        #text h1, #sidebar h3 {
        text-shadow: 2px 2px 3px #fff;
        color: #632dbd;
        }

        #text, #sidebar, #bottom {
        background-color: #00afea;
	      display: block;
	      max-width: 585px;
	      margin: auto;
	      border: 5px solid #fff;
	      padding: 15px;
        }
	    </style>

	    <!-- STYLESHEET 2 . . . Harston, Reed -->	
      <style>
        body {
        background-color: #304FFE;
        }  
        div#menuBar {
        background-color: #FF8E12;
        position: fixed;
        top: 8px;
        right: 8px;
        width: 10%;
        font-size: 16px;
        z-index: 99;
        }    

        ul#menuBarList {
        list-style-type: none;
        margin: 0;
        padding: 0;
        }
        #menuBarList :nth-child(2) {font-weight: bold; order:1;}

        .menuBarItem:hover {
        font-weight: bolder;
        }

        div#title   {
        background-color: #FFE012;
        }
        div#sidebar  {
        background-color: white;
        position: fixed;
        top: 102px;
        right: 8px;
        width: 10%;
        height: 100%;
        }
        div#text h1, div#sidebar h3 {
        border: 1px solid black;
        background-color: #5872FE;
        padding: 0px 2px 0px 2px;
        }
        div#text, div#bottom {
        background-color: white;
        }
        div#text p, div#sidebar p {
        padding: 0px 2px 0px 2px;
        }

        #title, #text, #bottom {      
        width: 89%
        }
        #menuBar, #title, #sidebar, #text, #bottom {
        border: 2px ridge red;
        }
	    </style>

	    <!-- STYLESHEET 3 . . . Lambert, David -->	
      <style>
        /* Contribution: David Lambert - Initial styling */

        /* Create title with shadow and float the subtitle */
        body {
        background-color: #F0F0F0;
        font-family: Verdana, sans-serif;
        margin: 0;
        padding:0;
        }
        #title {
        background-color: #456990;
        color: #FFFFFF;
        padding: 1em;
        }
        #title h1 {
        display: inline;
        margin: 0;
        padding: 0;
        text-shadow: 6px 5px 2px #000000;
        text-transform: uppercase;
        }
        #title p {
        float: right;
        font-size: 12px;
        margin-top: 1em;
        margin: 0;
        padding: 0;
        }

        /* Change menu list into a right sidebar */
        #menuBar {
        background-color: #49DCB1;
        border: 1px solid #000000;
        float: right;
        font-size: 14px;
        margin: 0 1em 0 1em;
        padding: 0.5em;
        width: 10em;
        }
        #menuBarList {
        list-style: none;
        margin: 0;
        padding: 0;
        }
        #menuBarList :nth-of-type(3) {
        font-weight: bold;
        }
        .menuBarItem {
        padding: 0.25em;
        text-align: center;
        text-decoration: underline;
        }
        /* Make menu items look like clickable links */
        .menuBarItem:hover {
        background-color: #368B7C;
        border-radius: 2em;
        color: #FFFFFF;
        cursor: pointer;
        font-weight: bolder;
        }

        /* Make sequential elements look like nested boxes */
        #text {
        margin-top: 1em;
        }
        #text, #sidebar {
        padding: 0 1em 0 1em;
        }
        #text h1, #sidebar h3 {
        border: 1px solid #000000;
        font-size: 21px;
        margin: 0;
        padding: 0.2em 0 0.2em 0.5em;
        text-shadow: 2px 2px 2px #FFFFFF;
        }
        #text p, #sidebar p {
        background-color: #FFFFFF;
        border: 1px solid #000000;
        border-top: 0;
        margin: 0 0 1em 0;
        padding: 0.5em;
        }

        /* Give unique colors and shadows to each of the different boxes */
        #text h1:first-of-type {
        background-color: #EF767A;
        text-shadow: 2px 2px 2px #994C4E;
        }
        #text h1:last-of-type {
        background-color: #EEB868;
        text-shadow: 2px 2px 2px #AE864C;
        }
        #sidebar h3 {
        background-color: #43AD9B;
        text-shadow: 2px 2px 2px #28685D;
        }

        /* Footer (Also dynamically adds the missing assignment due date/time) */
        #bottom {
        background-color: #456990;
        color: #FFFFFF;
        font-size: 10px;
        padding: 0.5em;
        }
        #bottom::after {
        content: 'January 20, 2017 5PM MST';
        }
	    </style>

	    <!-- STYLESHEET 4 . . . Gregory, Donovan -->	
      <style> 
	    </style>	

	    <!-- -------------------------------------------------------------------------------------- -->

	    <script type="text/javascript" 
	            src="https://gc.kis.v2.scr.kaspersky-labs.com/D582A52F-799B-1A49-817B-AFDA1E9FF5E3/main.js" 
	            charset="UTF-8">
	    </script>

	    <link rel="stylesheet" crossorigin="anonymous" 
	          href="https://gc.kis.v2.scr.kaspersky-labs.com/3E5FF9E1ADFA-B718-94A1-B997-F25A285D/abn/main.css"/>

	    <script type="text/javascript" src="/d2l/common/math/MathML.js?v=10.6.8.4741-10" >	
	    </script>

	    <script type="text/javascript">document.addEventListener('DOMContentLoaded', 
		    function() 
		    { 
			  D2LMathML.DesktopInit('https://s.brightspace.com/lib/mathjax/2.6.1/MathJax.js?config=MML_HTMLorMML',
			  'https://s.brightspace.com/lib/mathjax/2.6.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML%2cSafe'); 
		    });
	    </script>

	    <script type="text/javascript">
		    function lti_launch( vars ) 
		    { 
			  var query = ''; 
			  for(var key in vars) 
			  { 
			  if(query.length == 0) 
			  { 
			  query += '?' + key + '=' + encodeURIComponent(vars[key]); 
			  } 
			  else 
			  { 
			  query += '&' + key + '=' + encodeURIComponent(vars[key]); 
			  } 
			  } 
			  location.replace( '/d2l/customization/pearsonlti/6606/Launch' + query ); 
		    }
	    </script>
    </head>

    <body>
      <div class="document">

        <div id="title">
          <h1>Week 03 : CSS</h1>
          <p>This page will demonstrate how to switch between different CSS stylesheets to achieve a given effect</p>
        </div> <!--title -->

        <div class="content">

          <div id="menuBar">
            <ul id="menuBarList">
              <li class="menuBarItem" onclick="applyStyle(0)">Stylesheet 1</li>
              <li class="menuBarItem" onclick="applyStyle(1)">Stylesheet 2</li>
              <li class="menuBarItem" onclick="applyStyle(2)">Stylesheet 3</li>
              <li class="menuBarItem" onclick="applyStyle(3)">Stylesheet 4</li>
              <li class="menuBarItem" onclick="disableStyles()">No Stylesheet</li>
            </ul>
          </div> <!-- menuBar -->

          <div id="text">
            <h1>Select the Stylesheet</h1>         
            <p>There are four stylesheets that you may select from. Each one will change the coloring, fonts, 
        		  and even the layout of the page. You can change the layout of this page by selecting different 
              stylesheets in the menu, or by selecting one of the following links:<br>
              <a href="#" onclick="applyStyle(0)">Stylesheet 1</a>,
              <a href="#" onclick="applyStyle(1)">Stylesheet 2</a>,
              <a href="#" onclick="applyStyle(2)">Stylesheet 3</a>,
              <a href="#" onclick="applyStyle(3)">Stylesheet 4</a>.
            </p>

            <h1>Instructions</h1>
            <p>Please modify this page to include a description of each stylesheet, including anything clever that 
        		  you did to achieve a given effect. Please also include the contributors to a given stylesheet.
            </p>
          </div> <!-- text -->

          <div id="sidebar">
            <h3>Grading</h3>
            <p>In order to get full credit for this assignment, you will need to demonstrate what you have learned 
        		  and how you helped your classmates. This means your contribution needs to be briefly described 
              on the page.
            </p>
          </div> <!--sidebar -->

        </div> <!-- content -->

        <div id="bottom">Submit this assignment by </div>

      </div> <!-- document -->

      <script>
        <!-- DISABLE STYLES: This function turns off the four stylesheets -->
        function disableStyles() 
	      {
	      document.styleSheets[0].disabled = true;
	      document.styleSheets[1].disabled = true;
	      document.styleSheets[2].disabled = true;
	      document.styleSheets[3].disabled = true;
	      }
	      <!-- APPLY STYLES: This function turns off all four stylesheets, then turns one back on -->
	      function applyStyle(i)
	      {
		    disableStyles();
		    document.styleSheets[i].disabled = false;
	      }
      </script>
    </body>
  </html>
#+END_SRC
